### ISSUE TITLE
Turn off duplicate CI builds

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#317]
See https://github.com/orgs/community/discussions/26276 for a discussion.

I am trying:

```
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

```
