### ISSUE TITLE
update CI

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#411]
Some changes to the CI would be helpful.

This stops the extra build of the branch in every PR:

```
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

```
It's good to have the name of the job be the same as the name of the workflow.

Under strategy:

`     fail-fast: true
`

Also now we get gcovr from apt-get instead of using pip. This seems to resolve the breaking gcovr problems we have had on some repos but not others.

Also gcc_docs_test-coverage.yml is a relic from a previous round of CI development, which can be removed. Everything it does (and more) is now done by developer.yml.
